### ISSUE TITLE
How to debug with 74eo

### ISSUE THREAD

**Issue by xiaozhikang0916** [RadarNyan/CefEOBrowser#1]
How do you debug this project with 74EO? I tried "Attach to process" in Visual Studio but fail to load symbles and it won't pause when go into break point

**Comment by RadarNyan** [comment]
I have no trouble debugging it. (both "Attach to process" and break points work just fine)

Have you tried to make your own build? Or use your own reference BrowserLib.dll? Though I do not think latter would be necessary as I'm not using the same BrowserLib.dll as well.

**Comment by xiaozhikang0916** [comment]
Found the problem, I am using a release build of 74EO and thus missing the pdb of BrowserLib.

When I try a debug build it works fine

**Comment by xiaozhikang0916** [comment]
（主题无关）

请问你是没有上nga了吗，给你发了私信而没有回复（有点唐突）
因为这边没有什么提督开发者朋友所以希望能有个QQ讨论这样子...
