### ISSUE TITLE
74EO random freeze after replacing EOBrowser.exe with this project

### ISSUE THREAD

**Issue by RadarNyan** [RadarNyan/CefEOBrowser#2]
Currently (ab92b6d) the project runs just fine, for the most time. That being said, I've been experiencing random freeze of 74EO (not CefEOBrowser) with no clue what the cause is.

When 74EO freezes, all UI elements stops updating (like the timers) but CefEOBrowser keeps running (I can see the game animation and hear the BGM)

Sometimes if I wait for a few minutes it would recover, other times EOBrowser.exe just shuts down which leads to 74EO prompts me to exit.

**Comment by silfumus** [comment]
Any idea on how to replicate the issue?
Does it happen when you sortie or idle is enough to trigger the problem?

I haven't encountered such problem so far.

**Comment by RadarNyan** [comment]
@silfumus I can't reproduce it, hence the phrase "random".

It's likely triggered when the browser is making some sort of request and waiting for response, if it waits too long (due to poor network environment, proxy server problem...) and I if clicked on something other than the browser itself, inside or outside 74EO, it can even be triggered by 74EO notification popup.

Basically if the browser lost focus while waiting for certain response, then entire 74EO UI except the Browser would lock up. Although Browser is still running, neither the Browser nor other parts of 74EO (include browser toolbar) would response to my input.

Yet with all that being said, **I can't reproduce it.** I tried to put Fiddler in between and add break points before and after every /kcsapi/ request, no matter how long I wait, it just won't reproduce the problem.

**Comment by silfumus** [comment]
~~Ah, it's happening. Not freezing but `EOBrowser.exe` just shuts down unexpectedly.
I'll try searching for the problem. Seems to happen frequently if I left the `ToolMenu_Other_Navigate` dialog open.~~
Turns out it's a bug from my end and unrelated to the issue.

**Comment by ForsakenRei** [comment]
After switch to alpha4 I didn't encounter with any freezing or white screen yet. While the grey out is quite wired.  Yesterday I use Chrome with GPU acceleration and sometimes it still doesn't grey out. After I disable GPU acceleration of course the grey out effect is gone. But I refreshed the game and the effect is back. So I think it's more about the server, not just GPU accel.

P.S. Would you mind adding a switch or something so that people can disable GPU acceleration if they want? I usually use my GPU for some computing tasks and up to 25% is really a huge consumption. I know the possible downside of disable it and also I didn't stream or record so it should be fine(at least for me).

**Comment by RadarNyan** [comment]
@ForsakenRei The in-game "Gray Out" effect of destroyed ships and "Fade Out" effect of list items with long names are created with WebGL filters.

Technically, the said two effects would be gone if the game engine (PIXI.js) renders in Canvas mode (instead of WebGL mode). There could be a number of causes for that, disabling GPU acceleration is just one of them.

You can confirm this by open the developer console, currently in CefEOBrowser you can do that by using toolbar - others menu (3 dots) - Clear Cache (Yeah... I know it's weird) and switch to "Console" tab you'll see the welcome message from PIXI.js on the top of the list like this:

```PixiJS 4.8.1 - ✰ WebGL ✰```

Which indicates the Engine is rendering with WebGL, which should give you all the effects. If you don't have effects like "Gray out", you should be seeing a message contains "Canvas" which indicates it has fall back to using 2D rendering.

It's easy to add option for GPU acceleration, however disabling it would increase your CPU usage which really isn't all that good. I don't want to mess with 74eo's settings dialog, maybe I'll detect if a file named "nogpu" exists in the CefEOBrowser folder and show a warning message about it on start up. EDIT: implemented with a362c7f

**Comment by ForsakenRei** [comment]
@RadarNyan Tried with console and...alright let's wait for C2 to do something to those effects, misaligns and the insane memory leaking after long time playing for Chrome based viewers.
The file detection method is quite smart way. I just tested it and found about 6% more CPU usage as a tradeoff of nearly 15% GPU computing power. Thanks!

**Comment by xiaozhikang0916** [comment]
@ForsakenRei Have you found any rendering issue like not being gray of sinked enemy or fade-out effect like @RadarNyan mentioned? I also tried turning off GPU acceleration and nothing unexpected happened.

**Comment by ForsakenRei** [comment]
@xiaozhikang0916 not yet. Even using native Chrome without GPU acceleration sometimes I can still got gray/fade out. So as he said GPU acceleration might be only one of the causes for Canvas using 2D rendering.

**Comment by RadarNyan** [comment]
Close due to project cancellation.
