### ISSUE TITLE
In-game text appears higher than they should be

### ISSUE THREAD

**Issue by RadarNyan** [RadarNyan/CefEOBrowser#3]
This appears to be a upstream (Chromium) problem, nothing I can do about it, just wait for upstream to update (there's no way I can compile Chromium on this old laptop...)

* Cef Release (Chromium 65) renders higher
* Cef Pre-release (Chromium 67) renders higher
* Chromium 65 renders higher
* Google Chrome 68 renders correctly

**Comment by RadarNyan** [comment]
I tried to upgrade to latest CI build of CefSharp (https://www.myget.org/gallery/cefsharp) which is the same version as current Google Chrome, the problem persist. Then I grabbed the latest build of Chromium, tried, it also renders texts higher comparing to Google Chrome.

**So NO, this problem is not caused by using an old version (of Chromium).**

Not sure what the cause is, I have submitted a bug on chromium project: https://bugs.chromium.org/p/chromium/issues/detail?id=876977

**Comment by xiaozhikang0916** [comment]
Any pic of this issue? I am playing in stable version of Chrome in Mac, Windows and Android and debug build of this project but haven't come to this issue.

Have you tried other OS, graphics driver or toggle hardware acceleration setting?

**Comment by RadarNyan** [comment]
![image](https://user-images.githubusercontent.com/2091529/44510815-a70fea00-a6f0-11e8-8217-624601254f5a.png)
Up: Chromium (both the Chromium browser and Cef Project shows the same result.
Down: Google Chrome

I have not tried other OS myself but I have other people using difference OS (Windows 10) and reports seeing the same problem (not necessary using my project, other chromium based browser is also affected)

On my PC, both Google Chrome and Chromium shows the same info in both chrome://gpu and chrome://version
