### ISSUE TITLE
CefEOBrowser无法启动

### ISSUE THREAD

**Issue by kakei8142217** [RadarNyan/CefEOBrowser#6]
ver.beta-0.1.1 版本启动74EO后CefEOBrowser报错无法加载
[bugreport.txt](https://github.com/RadarNyan/CefEOBrowser/files/2320298/bugreport.txt)
另外alpha-3版本Windows不会报错，但74EO日志显示浏览器进程异常退出

**Comment by RadarNyan** [comment]
上传的日志文件显示加载 CefSharp.Core.dll 失败，请确认正确复制了 CefEOBrowser 文件夹。

alpha-3 之后的版本和我之前发布的汉化版 74EO 会有不兼容的情况，此问题在开发版已解决：
https://ci.appveyor.com/project/RadarNyan/electronicobserver-5xd4a/build/artifacts
（已经内置 CefEOBrowser）

**Comment by kakei8142217** [comment]
我确认正确复制了CefEOBrowser 文件夹，里面有CefSharp.Core.dll 
我还试着把CefEOBrowser 复制到原版74EO，一样会报错加载CefSharp.Core.dll 失败

开发版dev5会浏览器进程异常退出
[74EO_log.txt](https://github.com/RadarNyan/CefEOBrowser/files/2320401/74EO_log.txt)

**Comment by xiaozhikang0916** [comment]
你用的操作系统、.net framework版本以及杀毒、安全软件？

**Comment by kakei8142217** [comment]
OS-Windows 10 x64 1803
.net-3.5+4.7
杀软-Windows defender

**Comment by RadarNyan** [comment]
无法复现，请在崩溃后确认 CefEOBrowser\bin 目录下组件是否完整（正常应有 28 个文件 + 2 个文件夹）

**Comment by kakei8142217** [comment]
终于试出来了，万万没想到是缺C++2015
